1.9.0: More plain Result features
a-sit-plus/KmmResult pull request #10
Opened 2024-10-25 05:45 UTC by JesusMcCloud

- add WasmJS target
- add WasmWasi target
- add `wrappingPlain`, which works just like `wrapping` but on a `Result` rather than a `KmmResult` to avoid instantiation overhead
- rename `catchingUnwrapped` to `catchingPlain` to avoid confusions with `wrapping` but keep the old name as deprecated alternative
- add `nonFatalOrThrow`

2024-10-25 08:02 UTC, iaik-jheher requested changes
I'd suggest not renaming `catchingUnwrapped`, but renaming `wrapping`.
`catchingUnwrapped` matches `KmmResult<*>.unwrap(): Result<*>` and its inverse, `Result<*>.wrap(): KmmResult<*>`. This means that `wrapping` is the odd one out.

I'd suggest (the type parameter indicates the contained failure case, not the result type):
* `catching {...} -> KmmResult<*>`
* `catchingAs(a=::T) {...} -> KmmResult<out T>`
* `catchingUnwrapped {...} ->Result<*>`
* `catchingUnwrappedAs(a=::T) {...} -> Result<out T>`

In other words, `wrapping` becomes `catchingAs`, and the new `wrappingPlain` becomes `catchingUnwrappedAs`.

2024-10-25 09:50 UTC, JesusMcCloud commented on README.md
> +In addition, there's `catchingPlain` which directly returns an stdlib `Result`
also, its not called that anymore…

2024-10-25 09:53 UTC, iaik-jheher commented on README.md
> +In addition, there's `catchingPlain` which directly returns an stdlib `Result`
yes, also that :)

2024-10-25 15:52 UTC, iaik-jheher commented
@JesusMcCloud ready for review

2024-10-25 15:53 UTC, iaik-jheher commented
track [KT-72600](https://youtrack.jetbrains.com/issue/KT-72600/Contracts-are-not-transitive) for contract boilerplate

2024-10-25 16:12 UTC, iaik-jheher commented
track [KT-72601](https://youtrack.jetbrains.com/issue/KT-72601/LowPriorityInOverloadResolution-needed-for-constructor-reference-disambiguation) for `@Suppress` hackery

2024-10-25 19:46 UTC, JesusMcCloud commented
will release on Monday evening, unless someone objects

2024-10-28 11:17 UTC, nodh approved these changes

2024-10-28 11:17 UTC, nodh commented on CHANGELOG.md
> +- add WasmWasi target (not or KmmResult-test, as Kotest does not support WASI yet)
Typo in `or`?

2024-10-28 11:20 UTC, iaik-jheher approved these changes

2024-10-28 11:20 UTC, iaik-jheher commented on CHANGELOG.md
> +- add WasmWasi target (not or KmmResult-test, as Kotest does not support WASI yet)
```suggestion
- add WasmWasi target (not for KmmResult-test, as Kotest does not support WASI yet)
```

2024-10-28 17:32 UTC, merged